# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chief_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='adjusted_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
